# This workflow generates documentation (PDFs, CSV BOM, etc.) for when schematic was changed.

name: "KiBot - Generate KiCad Documentation For Changed Schematic"

on:
  workflow_call:
    inputs:
      # Set this to the base filename of your project.
      BaseFileName:
        required: true
        type: string

jobs:
  Schematic_Documentation_Update:
    env:
      # Set this to the output folder for all of the generated files. Unless you have a very
      # good reason to change this you should leave it as KiBotOutput.
      OutputFolder: KiBotOutput
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v3
        # Include submodules due to custom component library being a submodule.
        with:
          submodules: true

      # Run KiBot to generate schematic documentation.
      - name: Generate schematic documentation
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: .kibot/schematic_outputs.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: pcb/${{ inputs.BaseFileName }}.kicad_sch
          board: pcb/${{ inputs.BaseFileName }}.kicad_pcb

      # Archive all the artifacts from output and attach to the action's results.
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.BaseFileName }}-${{ github.event.inputs.version }}
          path: ${{ env.OutputFolder }}/**
