# This workflow generates documentation (PDFs, CSV BOM, etc.) for when schematic was changed.

name: "KiBot - Generate KiCad Documentation For Changed Schematic"

on:
  workflow_call:
    inputs:
      # Set this to the base filename of your project.
      KiCadProjectName:
        required: true
        type: string
      KiCadProjectDir:
        required: false
        type: string
        default: "."

jobs:
  Schematic_Documentation_Update:
    env:
      # Set this to the output folder for all of the generated files. Unless you have a very
      # good reason to change this you should leave it as KiBotOutput.
      OutputFolder: KiBotOutput
    runs-on: ubuntu-latest

    # These are all the steps that generate the files.
    steps:
      # Check out the files
      - uses: actions/checkout@v3
        # Include submodules due to custom component library being a submodule.
        with:
          submodules: true

      # Run KiBot to generate schematic documentation.
      - name: Generate schematic documentation
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: .kibot/schematic_change.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: ${{ inputs.KiCadProjectDir }}/${{ inputs.KiCadProjectName }}.kicad_sch
          board: ${{ inputs.KiCadProjectDir }}/${{ inputs.KiCadProjectName }}.kicad_pcb

      - name: Store short commit SHA
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Schematic Documentation
